# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preprocessing.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 495)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_tab1 = QtWidgets.QLabel(self.tab)
        self.label_tab1.setObjectName("label_tab1")
        self.verticalLayout_2.addWidget(self.label_tab1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labDEM_tab1 = QtWidgets.QLabel(self.tab)
        self.labDEM_tab1.setObjectName("labDEM_tab1")
        self.verticalLayout_3.addWidget(self.labDEM_tab1)
        self.txtDEM_tab1 = QtWidgets.QLineEdit(self.tab)
        self.txtDEM_tab1.setObjectName("txtDEM_tab1")
        self.verticalLayout_3.addWidget(self.txtDEM_tab1)
        self.labWats_tab1 = QtWidgets.QLabel(self.tab)
        self.labWats_tab1.setObjectName("labWats_tab1")
        self.verticalLayout_3.addWidget(self.labWats_tab1)
        self.txtWats_tab1 = QtWidgets.QLineEdit(self.tab)
        self.txtWats_tab1.setObjectName("txtWats_tab1")
        self.verticalLayout_3.addWidget(self.txtWats_tab1)
        self.labEpsg_tab1 = QtWidgets.QLabel(self.tab)
        self.labEpsg_tab1.setObjectName("labEpsg_tab1")
        self.verticalLayout_3.addWidget(self.labEpsg_tab1)
        self.txtEpsg_tab1 = QtWidgets.QLineEdit(self.tab)
        self.txtEpsg_tab1.setObjectName("txtEpsg_tab1")
        self.verticalLayout_3.addWidget(self.txtEpsg_tab1)
        self.labOutput_tab1 = QtWidgets.QLabel(self.tab)
        self.labOutput_tab1.setObjectName("labOutput_tab1")
        self.verticalLayout_3.addWidget(self.labOutput_tab1)
        self.txtOutput_tab1 = QtWidgets.QLineEdit(self.tab)
        self.txtOutput_tab1.setObjectName("txtOutput_tab1")
        self.verticalLayout_3.addWidget(self.txtOutput_tab1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.btnDEM_tab1 = QtWidgets.QPushButton(self.tab)
        self.btnDEM_tab1.setObjectName("btnDEM_tab1")
        self.verticalLayout_5.addWidget(self.btnDEM_tab1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.btnWats_tab1 = QtWidgets.QPushButton(self.tab)
        self.btnWats_tab1.setObjectName("btnWats_tab1")
        self.verticalLayout_5.addWidget(self.btnWats_tab1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.btnOutput_tab1 = QtWidgets.QPushButton(self.tab)
        self.btnOutput_tab1.setObjectName("btnOutput_tab1")
        self.verticalLayout_5.addWidget(self.btnOutput_tab1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.btnOk_tab1 = QtWidgets.QPushButton(self.tab)
        self.btnOk_tab1.setObjectName("btnOk_tab1")
        self.horizontalLayout_3.addWidget(self.btnOk_tab1)
        self.btnCancel_tab1 = QtWidgets.QPushButton(self.tab)
        self.btnCancel_tab1.setObjectName("btnCancel_tab1")
        self.horizontalLayout_3.addWidget(self.btnCancel_tab1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.label_tab2 = QtWidgets.QLabel(self.tab_2)
        self.label_tab2.setObjectName("label_tab2")
        self.verticalLayout_6.addWidget(self.label_tab2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labDEM_tab2 = QtWidgets.QLabel(self.tab_2)
        self.labDEM_tab2.setObjectName("labDEM_tab2")
        self.verticalLayout_9.addWidget(self.labDEM_tab2)
        self.txtDEM_tab2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtDEM_tab2.setObjectName("txtDEM_tab2")
        self.verticalLayout_9.addWidget(self.txtDEM_tab2)
        self.labOutput_tab2 = QtWidgets.QLabel(self.tab_2)
        self.labOutput_tab2.setObjectName("labOutput_tab2")
        self.verticalLayout_9.addWidget(self.labOutput_tab2)
        self.txtOutput_tab2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtOutput_tab2.setObjectName("txtOutput_tab2")
        self.verticalLayout_9.addWidget(self.txtOutput_tab2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem11)
        self.btnDEM_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.btnDEM_tab2.setObjectName("btnDEM_tab2")
        self.verticalLayout_8.addWidget(self.btnDEM_tab2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem12)
        self.btnOutput_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.btnOutput_tab2.setObjectName("btnOutput_tab2")
        self.verticalLayout_8.addWidget(self.btnOutput_tab2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.btnOk_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.btnOk_tab2.setObjectName("btnOk_tab2")
        self.horizontalLayout_4.addWidget(self.btnOk_tab2)
        self.btnCancel_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.btnCancel_tab2.setObjectName("btnCancel_tab2")
        self.horizontalLayout_4.addWidget(self.btnCancel_tab2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem15)
        self.label_tab3 = QtWidgets.QLabel(self.tab_3)
        self.label_tab3.setObjectName("label_tab3")
        self.verticalLayout_10.addWidget(self.label_tab3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem16)
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_10.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.txtNetwork_tab3 = QtWidgets.QLineEdit(self.tab_3)
        self.txtNetwork_tab3.setObjectName("txtNetwork_tab3")
        self.verticalLayout_11.addWidget(self.txtNetwork_tab3)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.txtDEM_tab3 = QtWidgets.QLineEdit(self.tab_3)
        self.txtDEM_tab3.setObjectName("txtDEM_tab3")
        self.verticalLayout_11.addWidget(self.txtDEM_tab3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self.btnNetwork_tab3 = QtWidgets.QPushButton(self.tab_3)
        self.btnNetwork_tab3.setObjectName("btnNetwork_tab3")
        self.verticalLayout_12.addWidget(self.btnNetwork_tab3)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem18)
        self.btnDEM_tab3 = QtWidgets.QPushButton(self.tab_3)
        self.btnDEM_tab3.setObjectName("btnDEM_tab3")
        self.verticalLayout_12.addWidget(self.btnDEM_tab3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem19)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.btnOk_tab3 = QtWidgets.QPushButton(self.tab_3)
        self.btnOk_tab3.setObjectName("btnOk_tab3")
        self.horizontalLayout_6.addWidget(self.btnOk_tab3)
        self.btnCancel_tab3 = QtWidgets.QPushButton(self.tab_3)
        self.btnCancel_tab3.setObjectName("btnCancel_tab3")
        self.horizontalLayout_6.addWidget(self.btnCancel_tab3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem21)
        self.label_tab4 = QtWidgets.QLabel(self.tab_4)
        self.label_tab4.setObjectName("label_tab4")
        self.verticalLayout_13.addWidget(self.label_tab4)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem22)
        self.line_4 = QtWidgets.QFrame(self.tab_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_13.addWidget(self.line_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.txtNetwork_tab4 = QtWidgets.QLineEdit(self.tab_4)
        self.txtNetwork_tab4.setObjectName("txtNetwork_tab4")
        self.verticalLayout_15.addWidget(self.txtNetwork_tab4)
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_15.addWidget(self.label_5)
        self.txtDEM_tab4 = QtWidgets.QLineEdit(self.tab_4)
        self.txtDEM_tab4.setObjectName("txtDEM_tab4")
        self.verticalLayout_15.addWidget(self.txtDEM_tab4)
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6)
        self.txtDA_tab4 = QtWidgets.QLineEdit(self.tab_4)
        self.txtDA_tab4.setObjectName("txtDA_tab4")
        self.verticalLayout_15.addWidget(self.txtDA_tab4)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.txtEpsg_tab4 = QtWidgets.QLineEdit(self.tab_4)
        self.txtEpsg_tab4.setObjectName("txtEpsg_tab4")
        self.verticalLayout_15.addWidget(self.txtEpsg_tab4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem23)
        self.btnNetwork_tab4 = QtWidgets.QPushButton(self.tab_4)
        self.btnNetwork_tab4.setObjectName("btnNetwork_tab4")
        self.verticalLayout_14.addWidget(self.btnNetwork_tab4)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem24)
        self.btnDEM_tab4 = QtWidgets.QPushButton(self.tab_4)
        self.btnDEM_tab4.setObjectName("btnDEM_tab4")
        self.verticalLayout_14.addWidget(self.btnDEM_tab4)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem25)
        self.btnDA_tab4 = QtWidgets.QPushButton(self.tab_4)
        self.btnDA_tab4.setObjectName("btnDA_tab4")
        self.verticalLayout_14.addWidget(self.btnDA_tab4)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem26)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem27)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem28)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.btnOk_tab4 = QtWidgets.QPushButton(self.tab_4)
        self.btnOk_tab4.setObjectName("btnOk_tab4")
        self.horizontalLayout_8.addWidget(self.btnOk_tab4)
        self.btnCancel_tab4 = QtWidgets.QPushButton(self.tab_4)
        self.btnCancel_tab4.setObjectName("btnCancel_tab4")
        self.horizontalLayout_8.addWidget(self.btnCancel_tab4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pre-processing Tools"))
        self.label_tab1.setText(_translate("MainWindow", "Projects a DEM into a coordinate reference system and then clips it to the extent of a selected watershed"))
        self.labDEM_tab1.setText(_translate("MainWindow", "DEM"))
        self.labWats_tab1.setText(_translate("MainWindow", "Watershed"))
        self.labEpsg_tab1.setText(_translate("MainWindow", "EPSG Number"))
        self.labOutput_tab1.setText(_translate("MainWindow", "Output DEM"))
        self.btnDEM_tab1.setText(_translate("MainWindow", ". . ."))
        self.btnWats_tab1.setText(_translate("MainWindow", ". . ."))
        self.btnOutput_tab1.setText(_translate("MainWindow", ". . ."))
        self.btnOk_tab1.setText(_translate("MainWindow", "OK"))
        self.btnCancel_tab1.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Watershed DEM"))
        self.label_tab2.setText(_translate("MainWindow", "Produces a drainage area raster where each cell value is contributing upstream area in square kilomters"))
        self.labDEM_tab2.setText(_translate("MainWindow", "DEM"))
        self.labOutput_tab2.setText(_translate("MainWindow", "Drainage Area Raster Ouptut"))
        self.btnDEM_tab2.setText(_translate("MainWindow", ". . ."))
        self.btnOutput_tab2.setText(_translate("MainWindow", ". . ."))
        self.btnOk_tab2.setText(_translate("MainWindow", "OK"))
        self.btnCancel_tab2.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Drainage Area"))
        self.label_tab3.setText(_translate("MainWindow", "Adds fields to an input drainage network representing network topology"))
        self.label_2.setText(_translate("MainWindow", "Drainage Network"))
        self.label_3.setText(_translate("MainWindow", "DEM"))
        self.btnNetwork_tab3.setText(_translate("MainWindow", ". . ."))
        self.btnDEM_tab3.setText(_translate("MainWindow", ". . ."))
        self.btnOk_tab3.setText(_translate("MainWindow", "OK"))
        self.btnCancel_tab3.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Network Topology"))
        self.label_tab4.setText(_translate("MainWindow", "Adds slope and drainage area attributes to an input drainage network"))
        self.label_4.setText(_translate("MainWindow", "Drainage Network"))
        self.label_5.setText(_translate("MainWindow", "DEM"))
        self.label_6.setText(_translate("MainWindow", "Drainage Area Raster"))
        self.label_8.setText(_translate("MainWindow", "EPSG Number"))
        self.btnNetwork_tab4.setText(_translate("MainWindow", ". . ."))
        self.btnDEM_tab4.setText(_translate("MainWindow", ". . ."))
        self.btnDA_tab4.setText(_translate("MainWindow", ". . ."))
        self.btnOk_tab4.setText(_translate("MainWindow", "OK"))
        self.btnCancel_tab4.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Network Attributes"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

